#!/usr/bin/env bash
# Script displays "Best School" 10 times but prints Hi at 9
c=0
while ((c < 10))
do
	((c++))
	if [ $c -eq 4 ]
	then
		echo "bad luck"
	elif [ $c -eq 8 ]
	then
		echo "good luck"
	else
		echo "Best School"
	fi
done
