#!/usr/bin/env bash
# Script displays "Best School" 10 times but prints Hi at 9
c=1
while ((c < 21))
do
	echo $c
	case "$c" in
		4) echo "bad luck from China";;
		9) echo "bad luck from Japan";;
		17) echo "bad luck from Italy";;
		esac
	((i++))
done
